import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import {Montserrat} from 'next/font/google'
import '@fancyapps/ui/dist/fancybox/fancybox.css';

import {config} from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import Header from "@/app/components/Layout/Header";
import Footer from "@/app/components/Layout/Footer";

config.autoAddCss = false

const roboto = Montserrat({
  subsets: ['latin'],
})

export const metadata = {
  title: "Спа-процедуры и массаж в спа-салоне Адлера",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="ru" className={roboto.className}>
    <body className='body tst'>
      <Header/>
      {children}
      <Footer/>


    </body>
    </html>
  );
}
